/**
 * C client stub to invoke services exported by the XML-RPC component: test.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project.
 *
 * Vortex Library homepage: http://vortex.aspl.es
 * Axl Library homepage: http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
#ifndef __XML_RPC_STRUCT_ITEM_H__
#define __XML_RPC_STRUCT_ITEM_H__

/* include base library */
#include <vortex.h>
/* include xml-rpc library */
#include <vortex_xml_rpc.h>
#include <test_types.h>

/* Item type declaration */
/* user definition declared at: test_types.h */
struct __Item {
	int position;
	char * string_position;
};

/* support for c++ declarations */
BEGIN_C_DECLS

/* (un)marshaller support functions  */
XmlRpcStruct * test_item_marshall (VortexCtx * _ctx_, Item * ref, axl_bool  dealloc);
Item * test_item_unmarshall (XmlRpcStruct * ref, axl_bool  dealloc);

/* memory (de)allocation functions */
Item * test_item_new (int position, const char * string_position);

Item * test_item_copy (Item * ref);

void test_item_free (Item * ref);

END_C_DECLS

#endif
