/**
 * C server skel to implement services exported by the XML-RPC
 * component: test.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project. 
 *
 * Vortex Library homepage:           http://vortex.aspl.es
 * Axl Library homepage:              http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
/* include base library */
#include <vortex.h>
/* include xml-rpc library */
#include <vortex_xml_rpc.h>
#include <test_types.h>

ItemArray * get_array_0 (char ** fault_error, int * fault_code, VortexChannel * channel)
{
	

		ItemArray * result;
		Item      * item;
		int         iterator;
		
		/* create the item array */
		result = test_itemarray_new (10);
		
		for (iterator = 0; iterator < 10; iterator++) {
			/* create the struct */
			item = test_item_new (iterator, "test content");
			
			/* store it into the array */
			test_itemarray_set (result, iterator, item);
		}
		
		/* put here service content */
		return result;		
	
}

/* This is a support function to invoke 'get_array' service , do not modify it!! */
XmlRpcMethodResponse * __get_array_0 (XmlRpcMethodCall * method_call, VortexChannel * channel)
{
	/* error support variables */
	VortexCtx * ctx         = METHOD_CALL_CTX(method_call);
	char      * fault_error = NULL;
	int         fault_code  = -1;
	ItemArray *    result = NULL;

	XmlRpcArray * _result;
	/* call to the user implementation */
	result = get_array_0 ( &fault_error, &fault_code, channel);

	/* check error reply looking at the fault_error */
	if (fault_error != NULL) {
		/* we have a error reply */
		return CREATE_FAULT_REPLY (fault_code, fault_error);
	}

	if (result == NULL) {
		/* we have a error reply */
		return CREATE_FAULT_REPLY (-2, "Returned a NULL value from a service which returns a pointer type. This is not allowed.");
	}

	/* Translate structure returned by the service */
	_result = test_itemarray_marshall (ctx, result, axl_true);

	/* return reply generated */
	return CREATE_OK_REPLY (ctx, XML_RPC_ARRAY_VALUE, _result);
}
