/**
 * C server skel to implement services exported by the XML-RPC
 * component: test.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project. 
 *
 * Vortex Library homepage:           http://vortex.aspl.es
 * Axl Library homepage:              http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
#ifndef __SERVER_TEST_GET_DOUBLE_SUM_XML_RPC_H__
#define __SERVER_TEST_GET_DOUBLE_SUM_XML_RPC_H__

/* include base library */
#include <vortex.h>
/* include xml-rpc library */
#include <vortex_xml_rpc.h>
#include <test_types.h>

double get_double_sum_2_double_double (double a, double b, char ** fault_error, int * fault_code, VortexChannel * channel);

XmlRpcMethodResponse * __get_double_sum_2_double_double (XmlRpcMethodCall * method_call, VortexChannel * channel);

#endif
