/**
 * C server skel to implement services exported by the XML-RPC
 * component: test.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project. 
 *
 * Vortex Library homepage:           http://vortex.aspl.es
 * Axl Library homepage:              http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
/* include base library */
#include <vortex.h>
/* include xml-rpc library */
#include <vortex_xml_rpc.h>
#include <test_types.h>

Node * get_list_0 (char ** fault_error, int * fault_code, VortexChannel * channel)
{
	
		/* the pointer result */
		Node * result;

		/* some variables for the service */
		Node * node;
		Node * next;
		int    iterator = 2;

		/* create the first node */
		result = test_node_new (1, NULL);
		node   = result;
		while (iterator < 10) {

			/* create the next, but setting next as NULL
			 * because we don't have it yet */
			next = test_node_new (iterator, NULL);

			/* set previous the next created */
			node->next = next;

			/* update references */
			node = next;

			/* update index */
			iterator ++;
		}
		
		/* return list created */
		return result;
	
}

/* This is a support function to invoke 'get_list' service , do not modify it!! */
XmlRpcMethodResponse * __get_list_0 (XmlRpcMethodCall * method_call, VortexChannel * channel)
{
	/* error support variables */
	VortexCtx * ctx         = METHOD_CALL_CTX(method_call);
	char      * fault_error = NULL;
	int         fault_code  = -1;
	Node *    result = NULL;

	XmlRpcStruct * _result;
	/* call to the user implementation */
	result = get_list_0 ( &fault_error, &fault_code, channel);

	/* check error reply looking at the fault_error */
	if (fault_error != NULL) {
		/* we have a error reply */
		return CREATE_FAULT_REPLY (fault_code, fault_error);
	}

	if (result == NULL) {
		/* we have a error reply */
		return CREATE_FAULT_REPLY (-2, "Returned a NULL value from a service which returns a pointer type. This is not allowed.");
	}

	/* Translate structure returned by the service */
	_result = test_node_marshall (ctx, result, axl_true);

	/* return reply generated */
	return CREATE_OK_REPLY (ctx, XML_RPC_STRUCT_VALUE, _result);
}
