/**
 * C client stub to invoke services exported by the XML-RPC component: test.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project.
 *
 * Vortex Library homepage: http://vortex.aspl.es
 * Axl Library homepage: http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
#ifndef __XML_RPC_STRUCT_NODE_H__
#define __XML_RPC_STRUCT_NODE_H__

/* include base library */
#include <vortex.h>
/* include xml-rpc library */
#include <vortex_xml_rpc.h>
#include <test_types.h>

/* Node type declaration */
/* user definition declared at: test_types.h */
struct __Node {
	int position;
	Node * next;
};

/* support for c++ declarations */
BEGIN_C_DECLS

/* (un)marshaller support functions  */
XmlRpcStruct * test_node_marshall (VortexCtx * _ctx_, Node * ref, axl_bool  dealloc);
Node * test_node_unmarshall (XmlRpcStruct * ref, axl_bool  dealloc);

/* memory (de)allocation functions */
Node * test_node_new (int position, Node * next);

Node * test_node_copy (Node * ref);

void test_node_free (Node * ref);

END_C_DECLS

#endif
