/* include example */
xml-rpc interface test {
	/* add two integers */
	int sum (int a, int b) {

		/* sum values received */
		return do_sum_operation (a, b);

	} options {
		include on body {
			int do_sum_operation (int a, int b) {
				return a + b;
			} /* do_sum_operation */
		} /* end include on body */
	}
}
