/**
 * C server skel to implement services exported by the XML-RPC
 * component: test.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project. 
 *
 * Vortex Library homepage:           http://vortex.aspl.es
 * Axl Library homepage:              http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
#include <test_sum_int_int.h>
#include <test_operate_int_int.h>
#include <test_get_the_string.h>
#include <test_get_the_bool_1.h>
#include <test_get_the_bool_2.h>
#include <test_get_double_sum_double_double.h>
#include <test_get_struct_values_values.h>
#include <test_get_array.h>
#include <test_get_list.h>
#include <test_sum2_int_int.h>


/* include xml-rpc library */
#include <vortex_xml_rpc.h>
XmlRpcMethodResponse *  service_dispatch (VortexChannel * channel, XmlRpcMethodCall * method_call, axlPointer user_data)
{

	/* check for a match for a service */
	if (method_call_is (method_call, "sum", 2, XML_RPC_INT_VALUE, XML_RPC_INT_VALUE,  -1))
		return __sum_2_int_int (method_call, channel);

	if (method_call_is (method_call, "operate", 2, XML_RPC_INT_VALUE, XML_RPC_INT_VALUE,  -1))
		return __operate_2_int_int (method_call, channel);

	if (method_call_is (method_call, "get_the_string", 0,  -1))
		return __get_the_string_0 (method_call, channel);

	if (method_call_is (method_call, "get_the_bool_1", 0,  -1))
		return __get_the_bool_1_0 (method_call, channel);

	if (method_call_is (method_call, "get_the_bool_2", 0,  -1))
		return __get_the_bool_2_0 (method_call, channel);

	if (method_call_is (method_call, "get_double_sum", 2, XML_RPC_DOUBLE_VALUE, XML_RPC_DOUBLE_VALUE,  -1))
		return __get_double_sum_2_double_double (method_call, channel);

	if (method_call_is (method_call, "get_struct", 2, XML_RPC_STRUCT_VALUE, XML_RPC_STRUCT_VALUE,  -1))
		return __get_struct_2_values_values (method_call, channel);

	if (method_call_is (method_call, "get_array", 0,  -1))
		return __get_array_0 (method_call, channel);

	if (method_call_is (method_call, "get_list", 0,  -1))
		return __get_list_0 (method_call, channel);

	if (method_call_is (method_call, "aritmetic-operations/basic/sum", 2, XML_RPC_INT_VALUE, XML_RPC_INT_VALUE,  -1))
		return __sum2_2_int_int (method_call, channel);

	/* return that the method to be invoked, is not supported or recognized by this module */
	return NULL;
}

