/**
 * C server skel to implement services exported by the XML-RPC
 * component: test.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project. 
 *
 * Vortex Library homepage:           http://vortex.aspl.es
 * Axl Library homepage:              http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
/* include base library */
#include <vortex.h>
/* include xml-rpc library */
#include <vortex_xml_rpc.h>
#include <test_types.h>

Values * get_struct_2_values_values (Values * a, Values * b, char ** fault_error, int * fault_code, VortexChannel * channel)
{
	
		Values * result;

		/* create the value to be returned */
		result = test_values_new (a->count    +  b->count, 
					  a->fraction +  b->fraction, 
					  a->status   || b->status);
		
		/* return the result provided */
		return result;
	
}

/* This is a support function to invoke 'get_struct' service , do not modify it!! */
XmlRpcMethodResponse * __get_struct_2_values_values (XmlRpcMethodCall * method_call, VortexChannel * channel)
{
	/* error support variables */
	VortexCtx * ctx         = METHOD_CALL_CTX(method_call);
	char      * fault_error = NULL;
	int         fault_code  = -1;
	Values *    result = NULL;

	XmlRpcStruct * _result;
	/* temporal variable declaration */
	axl_bool  unmarshall_failure = axl_false;

	/* marshall the struct parameter into a native type */
	Values * a = test_values_unmarshall (method_call_get_param_value_as_struct (method_call, 0), axl_false);
	/* marshall the struct parameter into a native type */
	Values * b = test_values_unmarshall (method_call_get_param_value_as_struct (method_call, 1), axl_false);
	if (a == NULL)
		unmarshall_failure = axl_true;
	if (b == NULL)
		unmarshall_failure = axl_true;
	
	/* call to the user implementation */
	if (! unmarshall_failure)
		result = get_struct_2_values_values (a, b,  &fault_error, &fault_code, channel);

	/* temporal variable deallocation */
	test_values_free (a);
	test_values_free (b);
	
	if (unmarshall_failure) {
		return CREATE_FAULT_REPLY (-1, "Found marshalling error. Unable to translate XML-RPC structures to native types");
	} /* end if */

	/* check error reply looking at the fault_error */
	if (fault_error != NULL) {
		/* we have a error reply */
		return CREATE_FAULT_REPLY (fault_code, fault_error);
	}

	if (result == NULL) {
		/* we have a error reply */
		return CREATE_FAULT_REPLY (-2, "Returned a NULL value from a service which returns a pointer type. This is not allowed.");
	}

	/* Translate structure returned by the service */
	_result = test_values_marshall (ctx, result, axl_true);

	/* return reply generated */
	return CREATE_OK_REPLY (ctx, XML_RPC_STRUCT_VALUE, _result);
}
