/**
 * C server skel to implement services exported by the XML-RPC
 * component: test.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project. 
 *
 * Vortex Library homepage:           http://vortex.aspl.es
 * Axl Library homepage:              http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
/* include base library */
#include <vortex.h>
/* include xml-rpc library */
#include <vortex_xml_rpc.h>
#include <test_types.h>

char * get_the_string_0 (char ** fault_error, int * fault_code, VortexChannel * channel)
{
	
		/* return a test string (static version) */
		return axl_strdup ("This is a test");
	
}

/* This is a support function to invoke 'get_the_string' service , do not modify it!! */
XmlRpcMethodResponse * __get_the_string_0 (XmlRpcMethodCall * method_call, VortexChannel * channel)
{
	/* error support variables */
	VortexCtx * ctx         = METHOD_CALL_CTX(method_call);
	char      * fault_error = NULL;
	int         fault_code  = -1;
	char *    result = NULL;

	/* call to the user implementation */
	result = get_the_string_0 ( &fault_error, &fault_code, channel);

	/* check error reply looking at the fault_error */
	if (fault_error != NULL) {
		/* we have a error reply */
		return CREATE_FAULT_REPLY (fault_code, fault_error);
	}

	if (result == NULL) {
		/* we have a error reply */
		return CREATE_FAULT_REPLY (-2, "Returned a NULL value from a service which returns a pointer type. This is not allowed.");
	}

	/* return reply generated */
	return CREATE_OK_REPLY (ctx, XML_RPC_STRING_REF_VALUE, result);
}
