/**
 * C client stub to invoke services exported by the XML-RPC component: test.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project.
 *
 * Vortex Library homepage: http://vortex.aspl.es
 * Axl Library homepage: http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
#ifndef __XML_RPC_ARRAY_ITEMARRAY_H__
#define __XML_RPC_ARRAY_ITEMARRAY_H__

/* include base library */
#include <vortex.h>
/* include xml-rpc library */
#include <vortex_xml_rpc.h>
#include <test_types.h>

/* support for c++ declarations */
BEGIN_C_DECLS

/* (un)marshaller support functions  */
XmlRpcArray    * test_itemarray_marshall   (VortexCtx * _ctx_, ItemArray * ref, axl_bool  dealloc);
ItemArray * test_itemarray_unmarshall (XmlRpcArray * ref, axl_bool  dealloc);

/* memory (de)allocation functions */
ItemArray * test_itemarray_new  (int count);
ItemArray * test_itemarray_copy (ItemArray * ref);
void test_itemarray_free (ItemArray * ref);

/* manipulation functions */
Item * test_itemarray_get (ItemArray * ref, int index);
void test_itemarray_set (ItemArray * ref, int index, Item * value);
void test_itemarray_add (ItemArray * ref, Item * value);

int test_itemarray_count (ItemArray * ref);

END_C_DECLS

#endif
