/**
 * C client stub to invoke services exported by the XML-RPC component: test.
 *
 * This file was generated by xml-rpc-gen tool, from Vortex Library
 * project.
 *
 * Vortex Library homepage: http://vortex.aspl.es
 * Axl Library homepage: http://xml.aspl.es
 * Advanced Software Production Line: http://www.aspl.es
 */
#ifndef __TEST_XML_RPC_TYPES_H__
#define __TEST_XML_RPC_TYPES_H__

/* Values type declaration */
typedef struct __Values Values;

/* Item type declaration */
typedef struct __Item Item;

/* ItemArray type declaration */
typedef struct __ItemArray ItemArray;

/* Node type declaration */
typedef struct __Node Node;

/* Values type interface */
#include <test_struct_values_xml_rpc.h>

/* Item type interface */
#include <test_struct_item_xml_rpc.h>

/* ItemArray type interface */
#include <test_array_itemarray_xml_rpc.h>

/* Node type interface */
#include <test_struct_node_xml_rpc.h>


#endif
